name: Check Makefiles

on:
  push:
    branches:
      - main
    paths:
      - "**/*Makefile*"
      - ".tools/checkmake"
      - ".tools/go.mod"
      - ".tools/go.sum"
      - ".github/workflows/check-makefile.yaml"
  pull_request:
    paths:
      - "**/*Makefile*"
      - ".tools/checkmake"
      - ".tools/go.mod"
      - ".tools/go.sum"
      - ".github/workflows/check-makefile.yaml"

jobs:
  checkmake:
    name: Check Makefile Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
        with:
          go-version-file: go.mod
      - run: mkdir -p .bin && cd .tools && go build -o ../.bin/checkmake github.com/checkmake/checkmake/cmd/checkmake
      - run: .bin/checkmake --config .tools/checkmake Makefile
